server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    platform: postgres
    # data: classpath:/sql/data.sql
    # schema: classpath:/sql/schema.sql
    driver-class-name: org.postgresql.Driver
    # initialization: always
    url: jdbc:postgresql://localhost:5432/evoluum
    password: codenation
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: true


authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
      id: orders
